# Generated by Django 3.0.4 on 2020-04-01 11:05

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command



class Migration(migrations.Migration):
    initial = True

    def load_users_from_fixture(apps, schema_editor):
        call_command("loaddata", "users")
        call_command("loaddata", "ActivePeriod")

    def delete_users(apps, schema_editor):
        user = apps.get_model("users", "user")
        users.objects.all().delete()
        activeperiod = apps.get_model("activeperiods", "activeperiod")
        ActivePeriod.objects.all().delete()

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_users_from_fixture,delete_users),
        ]
