# Generated by Django 3.0.4 on 2020-04-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_users_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeperiod',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activeperiod',
            name='start_time',
            field=models.DateField(),
        ),
    ]
