# Generated by Django 3.0.4 on 2020-04-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_auto_20200401_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='usersdata',
        ),
    ]
